In [1]:
import numpy as np

In [3]:
arr = np.array([1,2,3,4,5])
print(arr, type(arr))

[1 2 3 4 5] <class 'numpy.ndarray'>


# Python List Vs Numpy Array

- Numpy Array are faster (Because numpy optimized in c Language)
- Numpy store element in contiguous memory
- use less memory
- build in mathematical function
- support direct vectorized operation

In [7]:
# Execution speed
import time

py_list = list(range(1_000_000))
start = time.time()
sq_list = [x for x in py_list]
end = time.time()

print(f"The time taken by list is : {end-start} seconds")

np_arr = np.arange(1_000_000)
start = time.time()
sq_arr = np_arr ** 2
end = time.time()
print(f"The time taken by numpy array is : {end-start} secconds")

The time taken by list is : 0.04174947738647461 seconds
The time taken by numpy array is : 0.0027735233306884766 secconds


In [8]:
# Memory

import sys

print(f"size of list = {sys.getsizeof(py_list) * len(py_list)} bytes")
print(f"size of array = {np_arr.nbytes}")

size of list = 8000056000000 bytes
size of array = 8000000


# Creating Numpy Array

In [10]:
# from list

np_arr = np.array([34,54,34,23,1,2])
arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])

print(np_arr,np_arr.shape)
print(arr_2d,arr_2d.shape)

[34 54 34 23  1  2] (6,)
[[1 2 3]
 [4 5 6]
 [7 8 9]] (3, 3)


In [13]:
arr2 = np.array([1,2,3,4,5,"Prime"])
arr2

array(['1', '2', '3', '4', '5', 'Prime'], dtype='<U21')