In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4,5])
print(arr, type(arr))

[1 2 3 4 5] <class 'numpy.ndarray'>


# Python List Vs Numpy Array

- Numpy Array are faster (Because numpy optimized in c Language)
- Numpy store element in contiguous memory
- use less memory
- build in mathematical function
- support direct vectorized operation

In [3]:
# Execution speed
import time

py_list = list(range(1_000_000))
start = time.time()
sq_list = [x for x in py_list]
end = time.time()

print(f"The time taken by list is : {end-start} seconds")

np_arr = np.arange(1_000_000)
start = time.time()
sq_arr = np_arr ** 2
end = time.time()
print(f"The time taken by numpy array is : {end-start} secconds")

The time taken by list is : 0.031138181686401367 seconds
The time taken by numpy array is : 0.002613067626953125 secconds


In [4]:
# Memory

import sys

print(f"size of list = {sys.getsizeof(py_list) * len(py_list)} bytes")
print(f"size of array = {np_arr.nbytes}")

size of list = 8000056000000 bytes
size of array = 8000000


# Creating Numpy Array

In [5]:
# from list

np_arr = np.array([34,54,34,23,1,2])
arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])

print(np_arr,np_arr.shape)
print(arr_2d,arr_2d.shape)

[34 54 34 23  1  2] (6,)
[[1 2 3]
 [4 5 6]
 [7 8 9]] (3, 3)


In [6]:
arr2 = np.array([1,2,3,4,5,"Prime"])
arr2

array(['1', '2', '3', '4', '5', 'Prime'], dtype='<U21')

In [13]:
# Creating array from scratch
arr = np.array([1, 2, 3, 4, 5])
print("Array:", arr)

arr = np.zeros((3, 4))
print("Zeros array:", arr)

arr = np.ones((2, 3))
print("Ones array:", arr)

arr = np.full((2, 3), 7)
print("Full array:", arr)

arr = np.eye(3)
print("Identity array:", arr)

arr = np.arange(0, 10, 2, dtype="int64")
print("Arange array:", arr)

arr = np.linspace(0, 10, 5)  # Linspace generates 5 evenly spaced numbers between 0 and 10
print("Linspace array:", arr)

Array: [1 2 3 4 5]
Zeros array: [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Ones array: [[1. 1. 1.]
 [1. 1. 1.]]
Full array: [[7 7 7]
 [7 7 7]]
Identity array: [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Arange array: [0 2 4 6 8]
Linspace array: [ 0.   2.5  5.   7.5 10. ]


In [16]:
# Properties of numpy arrays
arr = np.array([[1, 2, 3], [4, 5, 6]])
print("Array:", arr)

print("Shape:", arr.shape)
print("Size:", arr.size) # Number of elements in the array
print("Data type:", arr.dtype) # data type of the elements in the array
print("Number of dimensions:", arr.ndim)    # Number of dimensions of the array
print("Item size:", arr.itemsize) # Size of each element in bytes
print("Total bytes:", arr.nbytes) # Total number of bytes consumed by the array

float_arr = np.array([1,2,3,4,5]).astype(np.float64)
print("Float array:", float_arr)
print("Float array data type:", float_arr.dtype)


Array: [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Size: 6
Data type: int64
Number of dimensions: 2
Item size: 8
Total bytes: 48
Float array: [1. 2. 3. 4. 5.]
Float array data type: float64


In [18]:
# Operations on numpy arrays
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7, 8, 9], [10, 11, 12]])

# Element-wise addition
result_add = arr1 + arr2
print("Addition:\n", result_add)

# Element-wise multiplication
result_mul = arr1 * arr2
print("Multiplication:\n", result_mul)

# Matrix multiplication
result_matmul = np.dot(arr1, arr2.T)  # Transpose arr2 for proper matrix multiplication
print("Matrix Multiplication:\n", result_matmul)

print(arr1 @ arr2.T) # Another way to do matrix multiplication

# Reshaping and indexing
arr = np.arange(1, 13).reshape((3, 4))
print("Original array:\n", arr) 
print("Reshaped array:\n", arr.reshape((4, 3)))


Addition:
 [[ 8 10 12]
 [14 16 18]]
Multiplication:
 [[ 7 16 27]
 [40 55 72]]
Matrix Multiplication:
 [[ 50  68]
 [122 167]]
[[ 50  68]
 [122 167]]
Original array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Reshaped array:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [19]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# flatten the array
flat_arr = arr.flatten()
print("Flattened array:", flat_arr)

Flattened array: [1 2 3 4 5 6 7 8 9]


In [21]:
# indexing

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
# Accessing a specific element
element = arr[1, 2]  # Access the element at row 1, column 2
print("Element at row 1, column 2:", element)

print("Accessing a specific row:", arr[1])  # Access the second row
print("Accessing a specific column:", arr[:, 2])  # Access the third column


Element at row 1, column 2: 6
Accessing a specific row: [4 5 6]
Accessing a specific column: [3 6 9]


In [23]:
# Fancy and boolean indexing

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2 = np.array([1,2,3,4,5,6,6,7,8,9,10
                ])

# Boolean indexing
mask = arr > 5  # Create a boolean mask for elements greater than 5
print("Boolean mask:", mask)
print("Elements greater than 5:", arr[mask])

print(arr[arr % 2 == 0])  # Elements that are even


Boolean mask: [[False False False]
 [False False  True]
 [ True  True  True]]
Elements greater than 5: [6 7 8 9]
[2 4 6 8]


In [26]:
# Fancy indexing
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
index = [0, 2]  # Indices of the rows we want to select
print("Elements at rows 0 and 2:", arr[index])

print(arr[[1,1,1]]) # Selecting the second row three times using fancy indexing

Elements at rows 0 and 2: [[1 2 3]
 [7 8 9]]
[[4 5 6]
 [4 5 6]
 [4 5 6]]


In [27]:
# Combining fancy and boolean indexing
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
# Fancy indexing to select rows 0 and 2
index = [0, 2]
fancy_selected = arr[index]
# Boolean indexing to select elements greater than 5 in the fancy selected rows
mask = fancy_selected > 5
print("Boolean mask:", mask)
print("Elements greater than 5 in the fancy selected rows:", fancy_selected[mask])


Boolean mask: [[False False False]
 [ True  True  True]]
Elements greater than 5 in the fancy selected rows: [7 8 9]


In [34]:
# Slicing
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
# Slicing rows and columns
sliced = arr[0:2, 1:3]
print("Sliced array:", sliced)

# Simple slicing
arr = np.array([1, 2, 3, 4, 5])
print("Sliced array:", arr[1:4])  # Slicing from index 1 to 3
print("Sliced array with step:", arr[0:5:2])  # Slicing with a step of 2
print("Sliced array from the end:", arr[-3:-1])  # Slicing from the third-to-last to the second-to-last element
print("end=", arr[-1])  # Accessing the last element
print("Sliced array with step:", arr[::2])  # Slicing with a step of 2

Sliced array: [[2 3]
 [5 6]]
Sliced array: [2 3 4]
Sliced array with step: [1 3 5]
Sliced array from the end: [3 4]
end= 5
Sliced array with step: [1 3 5]
