# Working with Vectors, Matrices, and Arrays in NumPy

> NumPy is a foundational tool of the Python machine learning stack. NumPy allows for efficient
> operations on the data structures often used in machine learning: vectors, matrices, and tensors.

In [1]:
# Creating Vector

# Load library
import numpy as np

# Create a vector as a row
vector_row = np.array([1, 2, 3])

# Create a vector as a column
vector_column = np.array([[1],
                          [2],
                          [3]])

print(vector_row)
print(vector_column)

[1 2 3]
[[1]
 [2]
 [3]]


NumPy’s main data structure is the multidimensional array. A vector is just an array with a
single dimension. To create a vector, we simply create a one-dimensional array. Just like vectors,
these arrays can be represented horizontally (i.e., rows) or vertically (i.e., columns).


In [3]:
# Creating a Matrix

# Load library
import numpy as np

# Create a matrix
matrix = np.array([[1, 2],
                   [1, 2],
                   [1, 2]])

In [6]:
# Creating a Sparse Matrix

# Load libraries
import numpy as np
from scipy import sparse

# Create a matrix
matrix = np.array([[0, 0],
                   [0, 1],
                   [3, 0]])

# Create compressed sparse row (CSR) matrix
matrix_sparse = sparse.csr_matrix(matrix)

print(matrix_sparse)


<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 2 stored elements and shape (3, 2)>
  Coords	Values
  (1, 1)	1
  (2, 0)	3


In [8]:
# Create larger matrix
matrix_large = np.array([[0, 0, 0, 0, 0, 8, 0, 0, 0, 0],
                         [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
                         [3, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

# Create compressed sparse row (CSR) matrix
matrix_large_sparse = sparse.csr_matrix(matrix_large)

# View original sparse matrix
print(matrix_sparse)

# View larger sparse matrix
print(matrix_large_sparse)


<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 2 stored elements and shape (3, 2)>
  Coords	Values
  (1, 1)	1
  (2, 0)	3
<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 3 stored elements and shape (3, 10)>
  Coords	Values
  (0, 5)	8
  (1, 1)	1
  (2, 0)	3


# 🧮 Sparse Matrices

> **Key idea:** A sparse matrix is a matrix in which most elements are zero.
> Instead of storing all the zeros, sparse matrix representations focus on storing the **non-zero values and the information needed to locate them**.

---

## 🎯 Why Sparse Matrices Matter

A common situation in **Machine Learning** is working with datasets that contain a huge number of features, where most feature values are `0`.

For example, imagine a **Netflix movie-watching matrix**:

* 👤 **Rows** → Netflix users
* 🎬 **Columns** → Movies
* 🔢 **Values** → Number of times a user watched a movie

The matrix could contain:

* Millions of users
* Tens of thousands of movies
* Billions of possible user–movie combinations

However, a user watches only a tiny fraction of all available movies.

Therefore, most values in the matrix would be `0`.

### Example

```text
              Movie A   Movie B   Movie C   Movie D   Movie E
User 1           0         0         3         0         0
User 2           1         0         0         0         0
User 3           0         0         0         0         2
User 4           0         0         0         0         0
```

Most of the matrix consists of zeros.

This is called **sparse data**.

---

## 💡 What Is a Sparse Matrix?

A **sparse matrix** is a matrix in which the majority of elements are `0`.

Instead of storing every element—including thousands or millions of zeros—a sparse representation stores information primarily about the **non-zero elements**.

This can provide significant benefits in:

* 💾 Memory usage
* ⚡ Computational efficiency
* 📊 Large-scale data processing
* 🤖 Machine Learning
* 🔍 Recommendation systems
* 📝 Natural Language Processing

### Dense vs Sparse

```text
Dense Matrix
┌───────────────────────┐
│ 0  0  0  0  0  0  0 │
│ 0  1  0  0  0  0  0 │
│ 3  0  0  0  0  0  0 │
└───────────────────────┘

Stores → ALL elements


Sparse Representation
┌─────────────────┐
│ (1, 1) → 1      │
│ (2, 0) → 3      │
└─────────────────┘

Stores → NON-ZERO elements
```

---

# 🔬 Creating a Sparse Matrix with SciPy

For sparse matrices, **SciPy** provides several specialized data structures.

```python
import numpy as np
from scipy import sparse
```

---

## 1️⃣ Create a Dense Matrix

Let's begin with a small NumPy matrix containing only two non-zero values.

```python
matrix = np.array([
    [0, 0],
    [0, 1],
    [3, 0]
])

matrix
```

### Matrix

```text
[[0 0]
 [0 1]
 [3 0]]
```

---

## 2️⃣ Convert the Matrix to CSR Format

We can convert the dense matrix into a **Compressed Sparse Row (CSR)** matrix.

```python
matrix_sparse = sparse.csr_matrix(matrix)

matrix_sparse
```

---

## 🔍 Viewing the Sparse Matrix

```python
print(matrix_sparse)
```

Output:

```text
  (1, 1)    1
  (2, 0)    3
```

Notice that the zeros are not explicitly listed.

The sparse representation records:

```text
(1, 1) → 1
(2, 0) → 3
```

---

# 📍 Understanding the Coordinates

The coordinates use **zero-based indexing**, just like NumPy.

```text
(1, 1) → 1
```

means:

* Row → `1`
* Column → `1`
* Value → `1`

Therefore, `1` is located at the **second row and second column**.

Similarly:

```text
(2, 0) → 3
```

means:

* Row → `2`
* Column → `0`
* Value → `3`

Therefore, `3` is located at the **third row and first column**.

---

## 🧠 Visualizing the Matrix

```text
             Column
              0   1
            ┌───────┐
Row 0       │ 0   0 │
Row 1       │ 0   1 │  ← (1, 1)
Row 2       │ 3   0 │  ← (2, 0)
            └───────┘
```

---

# 🚀 Why Sparse Representation Is Useful

Let's create a larger matrix.

```python
matrix_large = np.array([
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
    [3, 0, 0, 0, 0, 0, 0, 0, 0, 0]
])
```

This matrix now contains:

* `3` rows
* `10` columns
* `30` total elements
* Only `2` non-zero elements

---

## 3️⃣ Convert the Larger Matrix to CSR

```python
matrix_large_sparse = sparse.csr_matrix(matrix_large)

print(matrix_large_sparse)
```

Output:

```text
  (1, 1)    1
  (2, 0)    3
```

---

# 🔎 Comparing the Two Sparse Matrices

```python
print("Original sparse matrix:")
print(matrix_sparse)

print("\nLarger sparse matrix:")
print(matrix_large_sparse)
```

Output:

```text
Original sparse matrix:
  (1, 1)    1
  (2, 0)    3

Larger sparse matrix:
  (1, 1)    1
  (2, 0)    3
```

### 🤔 What happened?

Although we added many more zero elements, the sparse representation still contains only:

```text
(1, 1) → 1
(2, 0) → 3
```

The additional zeros do not need to be explicitly stored in the sparse representation.

---

# 📊 Dense vs Sparse Representation

| Property                         | Dense Matrix | Sparse Matrix        |
| -------------------------------- | ------------ | -------------------- |
| Stores zeros                     | ✅ Yes        | Usually ❌ No         |
| Stores non-zero values           | ✅ Yes        | ✅ Yes                |
| Memory efficient for sparse data | ❌            | ✅                    |
| Good for mostly-zero data        | ❌            | ✅                    |
| Easy to inspect directly         | ✅            | ⚠️ Depends on format |
| Common in ML                     | Sometimes    | Very common          |

> ⚠️ Sparse matrices are most useful when the matrix contains **many zeros relative to non-zero values**.

---

# 📐 Different Sparse Matrix Formats

CSR is only **one** sparse matrix representation.

Other commonly encountered formats include:

### 🔹 CSR — Compressed Sparse Row

Efficient for:

* Row-based operations
* Matrix-vector multiplication
* General sparse numerical computation

```python
sparse.csr_matrix(matrix)
```

---

### 🔹 CSC — Compressed Sparse Column

A column-oriented compressed format.

```python
sparse.csc_matrix(matrix)
```

Useful when operations are frequently performed **column-wise**.

---

### 🔹 LIL — List of Lists

Stores non-zero elements using lists for each row.

```python
sparse.lil_matrix(matrix)
```

Useful for:

* Incrementally constructing sparse matrices
* Modifying individual elements

---

### 🔹 DOK — Dictionary of Keys

Stores elements using dictionary-style `(row, column)` keys.

```python
sparse.dok_matrix(matrix)
```

Useful when:

* Building a sparse matrix incrementally
* Performing individual element updates

---

# 🧠 Choosing a Sparse Format

There is no universally **"best"** sparse matrix format.

The appropriate format depends on what you need to do with the matrix.

```text
                    Sparse Matrix
                         │
          ┌──────────────┼──────────────┐
          │              │              │
       Compute        Construct       Modify
          │              │              │
         CSR          LIL / DOK       LIL / DOK
          │
          ▼
      Efficient
      Operations
```

### General Rule

| Goal                       | Common Choice |
| -------------------------- | ------------- |
| General computation        | CSR           |
| Column-oriented operations | CSC           |
| Incremental construction   | LIL           |
| Individual element updates | DOK           |

> These are general guidelines rather than strict rules. The best format depends on the operations your application performs.

---

# 🤖 Sparse Matrices in Machine Learning

Sparse matrices appear frequently in real-world ML systems.

### 📝 Natural Language Processing

A vocabulary may contain:

```text
100,000+ words
```

while an individual document may contain only:

```text
100–1,000 unique words
```

A document-term matrix can therefore become highly sparse.

---

### 🎬 Recommendation Systems

```text
Users × Movies
```

Most users interact with only a small subset of movies.

Therefore:

```text
Millions of users
×
Thousands of movies
=
Mostly zeros
```

Sparse representations can make this type of data much more manageable.

---

### 🔢 One-Hot Encoding

Suppose we have:

```text
Apple
Banana
Orange
Mango
...
```

If there are thousands of possible categories, each individual observation may contain only **one `1`** and thousands of `0`s.

That is highly sparse.

---

# 📈 Measuring Sparsity

A useful concept is the **sparsity ratio**.

We can calculate:

[
\text{Sparsity} =
\frac{\text{Number of Zero Elements}}
{\text{Total Number of Elements}}
]

For example:

```python
total_elements = matrix_large.size
zero_elements = np.count_nonzero(matrix_large == 0)

sparsity = zero_elements / total_elements

print(f"Sparsity: {sparsity:.2%}")
```

Output:

```text
Sparsity: 93.33%
```

This means approximately **93% of the matrix elements are zero**.

---

# 💾 Why This Can Save Memory

Consider a huge matrix:

```text
1,000,000 × 10,000
```

That represents:

[
10^{10}
]

possible elements.

If almost all of those values are zero, storing every single zero can waste enormous amounts of memory.

A sparse representation can instead focus on the relatively small number of non-zero entries.

### Conceptually

```text
Dense
────────────────────────────
0 0 0 0 0 0 0 0 0 0 0 ...
0 0 0 5 0 0 0 0 0 0 0 ...
0 0 0 0 0 0 2 0 0 0 0 ...
────────────────────────────
Store everything


Sparse
────────────────────────────
(1, 3) → 5
(2, 6) → 2
────────────────────────────
Store useful information
```

---

# ⚠️ Important Consideration

Sparse matrices are **not automatically better** than dense matrices.

If a matrix contains many non-zero values, sparse storage may provide little or no benefit and can sometimes introduce additional overhead.

Therefore:

> **Use sparse representations when the data is sufficiently sparse and the chosen format matches the operations you need to perform.**

---

# 🧪 Quick Experiment

Let's compare the number of elements with the number of non-zero values.

```python
total = matrix_large.size
non_zero = np.count_nonzero(matrix_large)
zero = total - non_zero

print("Total elements :", total)
print("Non-zero values:", non_zero)
print("Zero values    :", zero)
```

Expected output:

```text
Total elements : 30
Non-zero values: 2
Zero values    : 28
```

Only **2 out of 30 elements** are non-zero.

---

# 🧠 Key Takeaways

### Remember these points:

1. **Sparse matrix** → Matrix containing mostly zeros.
2. Sparse representations avoid explicitly storing most zero values.
3. **CSR** stands for **Compressed Sparse Row**.
4. Sparse matrix coordinates use **zero-based indexing**.
5. Sparse matrices can significantly reduce memory usage for highly sparse data.
6. SciPy provides multiple sparse matrix formats.
7. There is no universally best sparse format.
8. Choose a format based on the operations you need.
9. Sparse matrices are common in:

   * 🤖 Machine Learning
   * 📝 NLP
   * 🎬 Recommendation Systems
   * 🔢 One-Hot Encoding
   * 📊 Large-scale numerical computing
10. Sparse storage is most useful when the matrix contains **a very high proportion of zeros**.

---

> ### 💡 Final Principle
>
> **When your data is mostly zeros, don't waste resources treating all those zeros as meaningful information.**
>
> Sparse matrix representations allow us to work with large, mostly-zero datasets much more efficiently.


In [9]:
# Preallocating NumPy Arrays

# Load library
import numpy as np

# Generate a vector of shape (1,5) containing all zeros
vector = np.zeros(shape=5)

# View the matrix
print(vector)


[0. 0. 0. 0. 0.]


In [10]:
# Generate a matrix of shape (3,3) containing all ones
matrix = np.full(shape=(3,3), fill_value=1)
# View the vector
print(matrix)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


> Generating arrays prefilled with data is useful for a number of purposes, such as making code
> more performant or using synthetic data to test algorithms. In many programming languages,
> preallocating an array of default values (such as 0s) is considered common practice.


In [ ]:
# Selecting Elements

# Load library
import numpy as np

# Create row vector
vector = np.array([1, 2, 3, 4, 5, 6])

# Create matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
# Select third element of vector
vector[2]