# 📐 Matrices

## Linear Algebra for AI & Machine Learning

A **matrix** is a rectangular arrangement of numbers, symbols, or expressions organized into **rows and columns**.

Matrices are one of the fundamental building blocks of **Linear Algebra** and are extensively used in:

- 🤖 Machine Learning
- 🧠 Deep Learning
- 📊 Data Science
- 🖼️ Computer Vision
- 📈 Statistics
- ⚙️ Numerical Computing
- 🔄 Linear Transformations
- 🧮 Optimization

> 💡 **ML Perspective:** A matrix is not just a table of numbers. It can represent data, transformations, equations, and the parameters of machine-learning models.

# 1. What is a Matrix?

A matrix is a rectangular arrangement of elements organized into **rows** and **columns**.

For example:

$$
A =
\begin{bmatrix}
1 & 2 & 3 \\
4 & 5 & 6
\end{bmatrix}
$$

This matrix has:

- **2 rows**
- **3 columns**
- **6 elements**

Therefore, its dimensions are:

$$
A \in \mathbb{R}^{2 \times 3}
$$

### General Form

A matrix can be represented as:

$$
A =
\begin{bmatrix}
a_{11} & a_{12} & \cdots & a_{1n} \\
a_{21} & a_{22} & \cdots & a_{2n} \\
\vdots & \vdots & \ddots & \vdots \\
a_{m1} & a_{m2} & \cdots & a_{mn}
\end{bmatrix}
$$

where:

- $m$ = number of rows
- $n$ = number of columns
- $a_{ij}$ = element at row $i$, column $j$

Hence:

$$
A \in \mathbb{R}^{m \times n}
$$

In [22]:
import numpy as np

A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

A

array([[1, 2, 3],
       [4, 5, 6]])

In [23]:
print("Matrix:")
print(A)

print("\nShape:", A.shape)
print("Number of dimensions:", A.ndim)
print("Number of elements:", A.size)

Matrix:
[[1 2 3]
 [4 5 6]]

Shape: (2, 3)
Number of dimensions: 2
Number of elements: 6


# 2. Matrix Dimensions

The dimensions of a matrix are written as:

$$
\boxed{m \times n}
$$

where:

- $m$ → number of **rows**
- $n$ → number of **columns**

### Example

$$
A =
\begin{bmatrix}
1 & 2 & 3 \\
4 & 5 & 6
\end{bmatrix}
$$

Therefore:

$$
A \in \mathbb{R}^{2 \times 3}
$$

### Remember

> **Rows × Columns**

```text
        Columns
       ↓   ↓   ↓
     ┌───────────┐
Row 1│ 1   2   3 │
Row 2│ 4   5   6 │
     └───────────┘
       ↑
      Rows

```





In [24]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

rows, columns = A.shape

print("Rows:", rows)
print("Columns:", columns)
print("Dimensions:", f"{rows} × {columns}")
print("Total elements:", A.size)

Rows: 2
Columns: 3
Dimensions: 2 × 3
Total elements: 6


# 3. Matrix Elements

Each individual value inside a matrix is called an **element** or **entry**.

The element at row $i$ and column $j$ is represented as:

$$
a_{ij}
$$

where:

- $i$ → row index
- $j$ → column index

For example:

$$
A =
\begin{bmatrix}
10 & 20 & 30 \\
40 & 50 & 60
\end{bmatrix}
$$

Then:

$$
a_{12}=20
$$

because the value is located at:

- Row = 1
- Column = 2

> ⚠️ Mathematical notation usually starts indexing from **1**, while Python/NumPy indexing starts from **0**.

In [25]:
A = np.array([
    [10, 20, 30],
    [40, 50, 60]
])

# Python uses zero-based indexing
print("Element at row 1, column 2:", A[0, 1])
print("Element at row 2, column 3:", A[1, 2])

Element at row 1, column 2: 20
Element at row 2, column 3: 60


# 4. Types of Matrices

Common types of matrices include:

| Matrix Type | Description |
|---|---|
| Row Matrix | Contains only one row |
| Column Matrix | Contains only one column |
| Rectangular Matrix | Number of rows ≠ number of columns |
| Square Matrix | Number of rows = number of columns |
| Zero Matrix | All elements are zero |
| Diagonal Matrix | Non-diagonal elements are zero |
| Identity Matrix | Main diagonal contains 1s |
| Symmetric Matrix | $A=A^T$ |
| Triangular Matrix | Elements are zero on one side of the diagonal |

# 5. Row Matrix

A matrix containing exactly **one row** is called a **row matrix**.

$$
A =
\begin{bmatrix}
1 & 2 & 3 & 4
\end{bmatrix}
$$

Dimensions:

$$
1 \times 4
$$

It is also commonly called a **row vector**.

In [26]:
row_matrix = np.array([
    [1, 2, 3, 4]
])

print(row_matrix)
print("Shape:", row_matrix.shape)

[[1 2 3 4]]
Shape: (1, 4)


# 6. Column Matrix

A matrix containing exactly **one column** is called a **column matrix**.

$$
A =
\begin{bmatrix}
1 \\
2 \\
3 \\
4
\end{bmatrix}
$$

Dimensions:

$$
4 \times 1
$$

It is also called a **column vector**.

In [27]:
column_matrix = np.array([
    [1],
    [2],
    [3],
    [4]
])

print(column_matrix)
print("Shape:", column_matrix.shape)

[[1]
 [2]
 [3]
 [4]]
Shape: (4, 1)


# 7. Rectangular Matrix

A matrix is **rectangular** when the number of rows is different from the number of columns.

$$
m \neq n
$$

Example:

$$
A =
\begin{bmatrix}
1 & 2 & 3 \\
4 & 5 & 6
\end{bmatrix}
$$

Dimensions:

$$
2 \times 3
$$

Since:

$$
2 \neq 3
$$

the matrix is rectangular.

# 8. Square Matrix

A matrix is **square** when:

$$
m=n
$$

Example:

$$
A =
\begin{bmatrix}
1 & 2 \\
3 & 4
\end{bmatrix}
$$

Dimensions:

$$
2 \times 2
$$

Square matrices are particularly important because operations such as:

- Determinant
- Inverse
- Eigenvalues
- Eigenvectors
- Diagonalization

are primarily defined for square matrices.

In [28]:
square_matrix = np.array([
    [1, 2],
    [3, 4]
])

print(square_matrix)
print("Shape:", square_matrix.shape)

[[1 2]
 [3 4]]
Shape: (2, 2)


# 9. Zero Matrix

A **zero matrix** contains only zeros.

Example:

$$
0 =
\begin{bmatrix}
0 & 0 \\
0 & 0
\end{bmatrix}
$$

The zero matrix behaves like `0` under matrix addition:

$$
A + 0 = A
$$

In [29]:
zero_matrix = np.zeros((3, 3))

zero_matrix

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

# 10. Identity Matrix

The **identity matrix** is the matrix equivalent of the number `1`.

It contains:

- `1` on the main diagonal
- `0` everywhere else

For a $3 \times 3$ identity matrix:

$$
I =
\begin{bmatrix}
1 & 0 & 0 \\
0 & 1 & 0 \\
0 & 0 & 1
\end{bmatrix}
$$

Its most important property is:

$$
AI = IA = A
$$

when the dimensions are compatible.

In [30]:
I = np.eye(3)

print(I)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [31]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print("A:")
print(A)

print("\nA @ I:")
print(A @ I)

print("\nI @ A:")
print(I @ A)

A:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

A @ I:
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]

I @ A:
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


# 11. Diagonal Matrix

A **diagonal matrix** is a square matrix where every element outside the main diagonal is zero.

Example:

$$
D =
\begin{bmatrix}
2 & 0 & 0 \\
0 & 5 & 0 \\
0 & 0 & 7
\end{bmatrix}
$$

The diagonal elements are:

$$
2,\ 5,\ 7
$$

In [32]:
D = np.diag([2, 5, 7])

D

array([[2, 0, 0],
       [0, 5, 0],
       [0, 0, 7]])

# 12. Matrix Addition

Two matrices can be added only when they have the **same dimensions**.

Let:

$$
A =
\begin{bmatrix}
1 & 2 \\
3 & 4
\end{bmatrix}
$$

and:

$$
B =
\begin{bmatrix}
5 & 6 \\
7 & 8
\end{bmatrix}
$$

Then:

$$
A+B =
\begin{bmatrix}
1+5 & 2+6 \\
3+7 & 4+8
\end{bmatrix}
$$

Therefore:

$$
A+B =
\begin{bmatrix}
6 & 8 \\
10 & 12
\end{bmatrix}
$$

### Rule

$$
\boxed{\text{Same dimensions} \Rightarrow \text{Addition is possible}}
$$

In [33]:
A = np.array([
    [1, 2],
    [3, 4]
])

B = np.array([
    [5, 6],
    [7, 8]
])

A + B

array([[ 6,  8],
       [10, 12]])

# 13. Matrix Subtraction

Matrix subtraction is also performed element-by-element.

$$
A-B =
\begin{bmatrix}
a_{11}-b_{11} & a_{12}-b_{12} \\
a_{21}-b_{21} & a_{22}-b_{22}
\end{bmatrix}
$$

The matrices must have the same dimensions.

In [34]:
A - B

array([[-4, -4],
       [-4, -4]])

# 14. Scalar Multiplication

A matrix can be multiplied by a scalar.

For example:

$$
A=
\begin{bmatrix}
1&2\\
3&4
\end{bmatrix}
$$

Then:

$$
3A=
\begin{bmatrix}
3&6\\
9&12
\end{bmatrix}
$$

Every element is multiplied by the scalar.

In [35]:
3 * A

array([[ 3,  6],
       [ 9, 12]])

# 15. Matrix Multiplication

Matrix multiplication is different from element-wise multiplication.

Suppose:

$$
A_{m\times n}
$$

and:

$$
B_{n\times p}
$$

Then:

$$
AB
$$

is valid and produces a matrix of dimensions:

$$
m\times p
$$

### Dimension Rule

$$
(m\times n)(n\times p)
\rightarrow
(m\times p)
$$

The **inner dimensions must match**.

### Valid

$$
(2\times3)(3\times4)
\rightarrow
(2\times4)
$$

### Invalid

$$
(2\times3)(2\times4)
$$

because:

$$
3\neq2
$$

> ⭐ Remember: **Inner dimensions must match; outer dimensions determine the result.**

In [36]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

B = np.array([
    [1, 2],
    [3, 4],
    [3, 4]
])

C = A @ B


print("A shape:", A.shape)
print("B shape:", B.shape)
print("C shape:", C.shape)

print("\nA @ B:")
print(C)

A shape: (2, 3)
B shape: (3, 2)
C shape: (2, 2)

A @ B:
[[16 22]
 [37 52]]


# 16. Element-wise Multiplication vs Matrix Multiplication

These two operations are different:

### Element-wise multiplication

$$
A*B
$$

Each corresponding element is multiplied.

### Matrix multiplication

$$
AB
$$

Rows of the first matrix are multiplied with columns of the second matrix.

In NumPy:

```python
A * B

In [38]:
A = np.array([
    [1, 2],
    [3, 4]
])

B = np.array([
    [5, 6],
    [7, 8]
])

print("Element-wise multiplication:")
print(A * B)

print("\nMatrix multiplication:")
print(A @ B)

Element-wise multiplication:
[[ 5 12]
 [21 32]]

Matrix multiplication:
[[19 22]
 [43 50]]


# 17. Transpose of a Matrix

The **transpose** of a matrix swaps its rows and columns.

It is represented as:

$$
A^T
$$

Example:

$$
A=
\begin{bmatrix}
1&2&3\\
4&5&6
\end{bmatrix}
$$

Then:

$$
A^T=
\begin{bmatrix}
1&4\\
2&5\\
3&6
\end{bmatrix}
$$

Therefore:

$$
(m\times n)^T=(n\times m)
$$

In [39]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print("A:")
print(A)

print("\nTranspose of A:")
print(A.T)

A:
[[1 2 3]
 [4 5 6]]

Transpose of A:
[[1 4]
 [2 5]
 [3 6]]


# 18. Symmetric Matrix

A square matrix is **symmetric** if:

$$
\boxed{A=A^T}
$$

Example:

$$
A=
\begin{bmatrix}
1&2&3\\
2&4&5\\
3&5&6
\end{bmatrix}
$$

The matrix is symmetric because:

$$
A=A^T
$$

In [40]:
A = np.array([
    [1, 2, 3],
    [2, 4, 5],
    [3, 5, 6]
])

print("A:")
print(A)

print("\nIs A symmetric?")
print(np.array_equal(A, A.T))

A:
[[1 2 3]
 [2 4 5]
 [3 5 6]]

Is A symmetric?
True


# 19. Matrix as a Linear Transformation

One of the most important concepts in Linear Algebra is that a matrix can represent a **linear transformation**.

Suppose:

$$
x=
\begin{bmatrix}
x_1\\
x_2
\end{bmatrix}
$$

and:

$$
A=
\begin{bmatrix}
a_{11}&a_{12}\\
a_{21}&a_{22}
\end{bmatrix}
$$

Then:

$$
x'=Ax
$$

Expanding:

$$
\begin{bmatrix}
x_1'\\
x_2'
\end{bmatrix}
=
\begin{bmatrix}
a_{11}&a_{12}\\
a_{21}&a_{22}
\end{bmatrix}
\begin{bmatrix}
x_1\\
x_2
\end{bmatrix}
$$

which gives:

$$
x_1'=a_{11}x_1+a_{12}x_2
$$

$$
x_2'=a_{21}x_1+a_{22}x_2
$$

Therefore:

> A matrix can transform one vector into another vector.

```text
Input Vector
     │
     ▼
   Matrix A
     │
     ▼
Output Vector

     x ─────► Ax

```

This idea appears throughout:

- Computer Graphics
- Computer Vision
- Robotics
- Machine Learning
- Deep Learning
- Physics

In [41]:
A = np.array([
    [2, 0],
    [0, 3]
])

x = np.array([
    [1],
    [2]
])

x_transformed = A @ x

print("Original vector:")
print(x)

print("\nTransformed vector:")
print(x_transformed)

Original vector:
[[1]
 [2]]

Transformed vector:
[[2]
 [6]]


# 20. Matrix Inverse

For a square matrix $A$, its inverse is represented as:

$$
A^{-1}
$$

The inverse satisfies:

$$
AA^{-1}=A^{-1}A=I
$$

This is similar to ordinary numbers:

$$
5\times\frac{1}{5}=1
$$

However, **not every matrix has an inverse**.

For a square matrix:

$$
\det(A)\neq0
$$

is required for the matrix to be invertible.

If:

$$
\det(A)=0
$$

the matrix is **singular** and has no ordinary inverse.

In [42]:
A = np.array([
    [1, 2],
    [3, 4]
])

A_inverse = np.linalg.inv(A)

print("A:")
print(A)

print("\nA inverse:")
print(A_inverse)

print("\nA @ A_inverse:")
print(A @ A_inverse)

A:
[[1 2]
 [3 4]]

A inverse:
[[-2.   1. ]
 [ 1.5 -0.5]]

A @ A_inverse:
[[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]


# 21. Determinant

The **determinant** is a scalar value associated with a square matrix.

It is written as:

$$
\det(A)
$$

or:

$$
|A|
$$

For a $2\times2$ matrix:

$$
A=
\begin{bmatrix}
a&b\\
c&d
\end{bmatrix}
$$

the determinant is:

$$
\boxed{\det(A)=ad-bc}
$$

### Important Connection

$$
\det(A)=0
$$

means:

- $A$ is singular
- $A^{-1}$ does not exist
- The transformation collapses dimensions

In [43]:
A = np.array([
    [1, 2],
    [3, 4]
])

det_A = np.linalg.det(A)

print("Determinant:", det_A)

Determinant: -2.0000000000000004


# 22. Trace of a Matrix

The **trace** of a square matrix is the sum of its main diagonal elements.

It is written as:

$$
\operatorname{Tr}(A)
$$

For:

$$
A=
\begin{bmatrix}
2&4\\
3&5
\end{bmatrix}
$$

we have:

$$
\operatorname{Tr}(A)=2+5=7
$$

For an $n\times n$ matrix:

$$
\boxed{
\operatorname{Tr}(A)=
\sum_{i=1}^{n}a_{ii}
}
$$

In [44]:
A = np.array([
    [2, 4],
    [3, 5]
])

print("Trace:", np.trace(A))

Trace: 7


# 23. Matrix and Machine Learning

Matrices are everywhere in Machine Learning.

A dataset can be represented as a matrix:

$$
X\in\mathbb{R}^{m\times n}
$$

where:

- $m$ = number of samples
- $n$ = number of features

For example:

```text
             Features
          F1    F2    F3
       ┌─────────────────┐
Sample1│ 10    20    30   │
Sample2│ 15    25    35   │
Sample3│ 12    22    32   │
       └─────────────────┘


In [45]:
# Example ML dataset

X = np.array([
    [10, 20, 30],
    [15, 25, 35],
    [12, 22, 32]
])

print("Dataset:")
print(X)

print("\nSamples:", X.shape[0])
print("Features:", X.shape[1])

Dataset:
[[10 20 30]
 [15 25 35]
 [12 22 32]]

Samples: 3
Features: 3


# 24. Matrices in Neural Networks

Neural networks rely heavily on matrix multiplication.

A basic neural-network layer can be represented as:

$$
z=Wx+b
$$

where:

- $W$ → weight matrix
- $x$ → input vector
- $b$ → bias vector
- $z$ → output before activation

Then an activation function is applied:

$$
a=f(z)
$$

For a batch of inputs, matrix operations allow many samples to be processed simultaneously.

A simplified form is:

$$
Z=XW+b
$$

> 🧠 **Key Idea:** Matrix multiplication is one of the fundamental computational operations behind modern Deep Learning.

In [46]:
# Simple neural-network style computation

X = np.array([
    [1, 2],
    [3, 4],
    [5, 6]
])

W = np.array([
    [0.5, 0.2],
    [0.3, 0.8]
])

b = np.array([1, 2])

Z = X @ W + b

print("X:")
print(X)

print("\nW:")
print(W)

print("\nBias:")
print(b)

print("\nZ = XW + b:")
print(Z)

X:
[[1 2]
 [3 4]
 [5 6]]

W:
[[0.5 0.2]
 [0.3 0.8]]

Bias:
[1 2]

Z = XW + b:
[[2.1 3.8]
 [3.7 5.8]
 [5.3 7.8]]


# 25. Matrix Operations — Quick Reference

| Operation | NumPy | Meaning |
|---|---|---|
| Addition | `A + B` | Element-wise addition |
| Subtraction | `A - B` | Element-wise subtraction |
| Scalar multiplication | `c * A` | Multiply every element |
| Element-wise multiplication | `A * B` | Corresponding elements |
| Matrix multiplication | `A @ B` | Linear algebra multiplication |
| Transpose | `A.T` | Rows ↔ Columns |
| Inverse | `np.linalg.inv(A)` | Matrix inverse |
| Determinant | `np.linalg.det(A)` | Determinant |
| Trace | `np.trace(A)` | Diagonal sum |
| Shape | `A.shape` | Dimensions |
| Number of elements | `A.size` | Total elements |
| Identity matrix | `np.eye(n)` | $n\times n$ identity |
| Diagonal matrix | `np.diag(...)` | Diagonal matrix |

In [47]:
import numpy as np

A = np.array([
    [1, 2],
    [3, 4]
])

B = np.array([
    [5, 6],
    [7, 8]
])

# Addition
addition = A + B

# Subtraction
subtraction = A - B

# Scalar multiplication
scalar = 3 * A

# Element-wise multiplication
elementwise = A * B

# Matrix multiplication
matrix_multiplication = A @ B

# Transpose
transpose = A.T

# Determinant
determinant = np.linalg.det(A)

# Inverse
inverse = np.linalg.inv(A)

# Trace
trace = np.trace(A)

print("Addition:\n", addition)
print("\nSubtraction:\n", subtraction)
print("\nScalar Multiplication:\n", scalar)
print("\nElement-wise Multiplication:\n", elementwise)
print("\nMatrix Multiplication:\n", matrix_multiplication)
print("\nTranspose:\n", transpose)
print("\nDeterminant:", determinant)
print("\nInverse:\n", inverse)
print("\nTrace:", trace)

Addition:
 [[ 6  8]
 [10 12]]

Subtraction:
 [[-4 -4]
 [-4 -4]]

Scalar Multiplication:
 [[ 3  6]
 [ 9 12]]

Element-wise Multiplication:
 [[ 5 12]
 [21 32]]

Matrix Multiplication:
 [[19 22]
 [43 50]]

Transpose:
 [[1 3]
 [2 4]]

Determinant: -2.0000000000000004

Inverse:
 [[-2.   1. ]
 [ 1.5 -0.5]]

Trace: 5


# 🧠 Key Takeaways

### Fundamental Concepts

1. A matrix is a rectangular arrangement of elements.
2. Matrix dimensions are written as **rows × columns**.
3. $a_{ij}$ represents the element at row $i$, column $j$.
4. A square matrix has equal numbers of rows and columns.
5. A row matrix has one row.
6. A column matrix has one column.
7. A zero matrix contains only zeros.
8. An identity matrix behaves like `1` under matrix multiplication.
9. A diagonal matrix has zeros outside its main diagonal.

### Operations

10. Matrix addition requires equal dimensions.
11. Matrix multiplication requires matching inner dimensions.
12. `A * B` in NumPy performs element-wise multiplication.
13. `A @ B` performs matrix multiplication.
14. Transpose swaps rows and columns.
15. An inverse exists only for an invertible square matrix.
16. The determinant helps determine whether a square matrix is invertible.
17. The trace is the sum of the main diagonal.

### AI/ML Connection

18. Datasets can be represented as matrices.
19. Linear transformations can be represented using matrices.
20. Neural networks heavily rely on matrix multiplication.

> 🚀 **Don't just memorize matrix formulas. Understand what matrices do to vectors and data. This intuition becomes extremely important when learning Linear Regression, PCA, Neural Networks, Computer Vision, and Deep Learning.**